const STATS={"completed": 60, "total": 749, "gamePct": 0.08010680908, "achObtained": 924, "achTotal": 30826, "achPct": 0.02997469668}; let games=[]; let shown=24;
const $=s=>document.querySelector(s); const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
fetch('games.json').then(r=>r.json()).then(data=>{games=data;init();});
function init(){ $('#completedStat').textContent=STATS.completed;$('#totalStat').textContent=STATS.total;$('#pctStat').textContent=(STATS.gamePct*100).toFixed(1)+'%';$('#progressBar').style.width=(STATS.gamePct*100)+'%';$('#achievementStat').textContent=STATS.achObtained.toLocaleString();
const planned=games.reduce((a,g)=>a+(g.recommendedHours||0),0);$('#hoursStat').textContent=Math.round(planned).toLocaleString();
fill('#sizeFilter',[...new Set(games.map(g=>g.size))].sort()); fill('#typeFilter',[...new Set(games.map(g=>g.type))].sort()); render();}
function fill(sel,vals){vals.forEach(v=>{let o=document.createElement('option');o.value=v;o.textContent=v;$(sel).appendChild(o)})}
function filtered(){let q=$('#search').value.toLowerCase(),s=$('#sizeFilter').value,t=$('#typeFilter').value,st=$('#statusFilter').value;return games.filter(g=>(!q||g.name.toLowerCase().includes(q))&&(!s||g.size===s)&&(!t||g.type===t)&&(!st||(st==='complete'?g.completed:!g.completed)));}
function render(){let list=filtered();$('#resultCount').textContent=list.length.toLocaleString()+' games found';$('#gameGrid').innerHTML=list.slice(0,shown).map(g=>`<article class="game-card"><div><span class="hours">${g.recommendedHours==null?'?':g.recommendedHours}h</span><h3>${esc(g.name)}</h3><div class="meta">${esc(g.achievements)} achievements</div></div><div class="pills"><span class="pill ${g.completed?'done':''}">${g.completed?'COMPLETED':'BACKLOG'}</span><span class="pill">${esc(g.size)}</span><span class="pill">${esc(g.type)}</span></div></article>`).join('');$('#more').style.display=shown<list.length?'block':'none';}
['#search','#sizeFilter','#typeFilter','#statusFilter'].forEach(x=>$(x).addEventListener('input',()=>{shown=24;render()}));$('#more').onclick=()=>{shown+=24;render()};$('#reset').onclick=()=>{$('#search').value='';$('#sizeFilter').value='';$('#typeFilter').value='';$('#statusFilter').value='';shown=24;render()};
